# We can done thorugh 3 types :-
## 1. using pandas.get_dummies()
## 2. using sklearn.preprocessing.OneHotEncder
## 3. manually numpy

##### now we see second type that is using sklearn

In [3]:
from sklearn.preprocessing import OneHotEncoder

categories = ['Apple','banana','cherry','apple','Banana']
categories=[[cat] for cat in categories]

encoder = OneHotEncoder()
encoded = encoder.fit_transform(categories).toarray()

print("categories : ")
print(categories)

categories : 
[['Apple'], ['banana'], ['cherry'], ['apple'], ['Banana']]


In [4]:
print("\nOne-Hot Encode Array : ")
print(encoded)


One-Hot Encode Array : 
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [5]:
print("\nFeature names : ")
print(encoder.get_feature_names_out())


Feature names : 
['x0_Apple' 'x0_Banana' 'x0_apple' 'x0_banana' 'x0_cherry']
